version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3
    restart: on-failure
    expose:
      - "5672"
    volumes:
      - rabbitmq_etc/:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs/:/var/log/rabbitmq/
    
  mongodb:
    image: mongo:4
    restart: on-failure
    expose:
      - "27019"
    volumes:
      - mongodb:/data
        
  ui:
    image: mindcollapse/malware-multi-scan-ui
    restart: on-failure
    ports:
      - "8888:8888" 
    expose:
      - "8888"
    depends_on:
      - api
    environment:
      - "API_URL=http://api:5000"
      - "NUXT_HOST=0.0.0.0"
      - "NUXT_PORT=8888"
    build:
      context: MalwareMultiScan.Ui
      dockerfile: Dockerfile

  api:
    image: mindcollapse/malware-multi-scan-api
    restart: on-failure
    expose:
      - "5000"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - "ConnectionStrings__RabbitMQ=host=rabbitmq"
      - "ConnectionStrings__Mongo=mongodb://mongodb:27017"
      - "BackendsConfiguration=/etc/backends.yaml"
    volumes:
      - "./MalwareMultiScan.Api/backends.yaml:/etc/backends.yaml:ro"
    build:
      context: .
      dockerfile: MalwareMultiScan.Api/Dockerfile
  
  dummy-scanner:
    image: mindcollapse/malware-multi-scan-scanner-dummy
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - "ConnectionStrings__RabbitMQ=host=rabbitmq;prefetchcount=1"
    build:
      context: MalwareMultiScan.Backends/Dockerfiles
      dockerfile: Dummy.Dockerfile
  
  clamav-scanner:
    image: mindcollapse/malware-multi-scan-scanner-clamav
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - "ConnectionStrings__RabbitMQ=host=rabbitmq;prefetchcount=1"
    build:
      context: MalwareMultiScan.Backends/Dockerfiles
      dockerfile: Clamav.Dockerfile
      
  windows-defender-scanner:
    image: mindcollapse/malware-multi-scan-scanner-windows-defender
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - "ConnectionStrings__RabbitMQ=host=rabbitmq;prefetchcount=1"
    build:
      context: MalwareMultiScan.Backends/Dockerfiles
      dockerfile: WindowsDefender.Dockerfile

volumes:
  mongodb:
  rabbitmq_etc:
  rabbitmq_data:
  rabbitmq_logs: