version: "3"

services:
  clamav-backend:
    image: ${DOCKER_IMAGE_PREFIX-mindcollapse}/malware-multi-scan-worker-clamav
    build:
      context: MalwareMultiScan.Backends/Dockerfiles
      dockerfile: Clamav.Dockerfile
      
  windows-defender-backend:
    image: ${DOCKER_IMAGE_PREFIX-mindcollapse}/malware-multi-scan-worker-windows-defender
    build:
      context: MalwareMultiScan.Backends/Dockerfiles
      dockerfile: WindowsDefender.Dockerfile

# SCAN BACKENDS BELOW DISABLE DUE TO THE VENDOR LICENSING POLICY    
# RE-ENABLE ONLY AFTER CHECKING EULA POLICY & BUYING THE LICENSE
#
#  comodo-backend:
#    image: ${DOCKER_IMAGE_PREFIX-mindcollapse}/malware-multi-scan-worker-comodo
#    build:
#      context: MalwareMultiScan.Backends/Dockerfiles
#      dockerfile: Comodo.Dockerfile
#      
#  drweb-backend:
#    image: ${DOCKER_IMAGE_PREFIX-mindcollapse}/malware-multi-scan-worker-drweb
#    build:
#      context: MalwareMultiScan.Backends/Dockerfiles
#      dockerfile: DrWeb.Dockerfile
#      
#  kes-backend:
#    image: ${DOCKER_IMAGE_PREFIX-mindcollapse}/malware-multi-scan-worker-kes
#    build:
#      context: MalwareMultiScan.Backends/Dockerfiles
#      dockerfile: KES.Dockerfile
#      
#  mcafee-backend:
#    image: ${DOCKER_IMAGE_PREFIX-mindcollapse}/malware-multi-scan-worker-mcafee
#    build:
#      context: MalwareMultiScan.Backends/Dockerfiles
#      dockerfile: McAfee.Dockerfile
#      
#  sophos-backend:
#    image: ${DOCKER_IMAGE_PREFIX-mindcollapse}/malware-multi-scan-worker-sophos
#    build:
#      context: MalwareMultiScan.Backends/Dockerfiles
#      dockerfile: Sophos.Dockerfile