name: API

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - 'MalwareMultiScan.Api/**'

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: mindcollapse
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: MalwareMultiScan.Api/Dockerfile
          platforms: linux/amd64
          tags: mindcollapse/malware-multi-scan-api:latest